log_format timed '$remote_addr - $request '
                 'status=$status body_bytes=$body_bytes_sent '
                 'request_time=$request_time '
                 'upstream_time=$upstream_response_time '
                 'upstream_status=$upstream_status';

server {
    listen 80;
    server_name _;
    index index.php;
    root /var/www/public;
    access_log /var/log/nginx/access.log timed;

    # Compresión
    gzip on;
    gzip_types application/json text/plain text/css application/javascript;
    gzip_min_length 1024;

    # Timeouts explícitos
    fastcgi_read_timeout 120;
    fastcgi_send_timeout 120;

    # Buffers en memoria (evita escritura a disco)
    fastcgi_buffer_size        16k;
    fastcgi_buffers            4 16k;
    fastcgi_busy_buffers_size  32k;
    client_max_body_size 64M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass ops-node-api-php:9000;
        fastcgi_keep_conn on; # <- reutilizar conexiones FPM
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        # Headers recibidos desde Apache reverse proxy del host.
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
        fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for;
        fastcgi_param HTTP_X_REAL_IP $http_x_real_ip;
    }

    location ~ /\.ht {
        deny all;
    }
}
