server {
    listen 80;
    index index.php;
    root /var/www/public;

    # Compresión
    gzip on;
    gzip_types application/json text/plain text/css application/javascript;
    gzip_min_length 1024;

    # Timeouts explícitos
    fastcgi_read_timeout 120;
    fastcgi_send_timeout 120;

    # Buffers en memoria (evita escritura a disco)
    fastcgi_buffer_size        16k;
    fastcgi_buffers            4 16k;
    fastcgi_busy_buffers_size  32k;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass ops-node-api-php:9000;
        fastcgi_keep_conn on; # <- reutilizar conexiones FPM
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}